### ISSUE TITLE
Keywords file and override

### ISSUE THREAD

**Issue by deer** [deer/fresh_blog#14]
Pull out all the keywords into a separate file. There's probably a better word for this, but examples include:
* by
* next post
* previous page

Putting this into a file enables us to then provide overrides in the options. This could be useful if someone wants to have their blog be in a different language, and don't want a bunch of English words appearing everywhere!

**Comment by deer** [comment]
I've also included some arrow symbols (→) in the text as well, since I think it looks good. Other people might have different opinions, and this functionality could also be used to remove the arrows.

**Comment by scottyg** [comment]
@deer Im going to look into a solution for this today
